name: Simple Deploy

on:
  push:
    branches: [main]
    paths: ['blocks/course_list/**']
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          source: "blocks/course_list"
          target: "${{ secrets.MOODLE_PATH }}/blocks/"
          strip_components: 1

      - name: Set Permissions and Clear Cache
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ${{ secrets.MOODLE_PATH }}
            chmod -R 755 blocks/course_list
            chown -R www-data:www-data blocks/course_list
            php admin/cli/purge_caches.php 