name: Test Deploy Trigger

on:
  workflow_run:
    workflows: ["Verify Badge Plugin CI"]
    types:
      - completed
    branches:
      - master
      - main

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Workflow Trigger
        run: |
          echo "🔍 Testing workflow trigger..."
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Triggering Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          
      - name: Check if CI was successful
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "✅ CI workflow completed successfully - deployment should trigger!"
          else
            echo "❌ CI workflow did not complete successfully - deployment will not trigger"
            echo "CI Conclusion: ${{ github.event.workflow_run.conclusion }}"
          fi 